create table public.fantasy_provider_settings (
  id uuid primary key default gen_random_uuid(),
  competition_season_id uuid not null unique references public.competition_seasons(id) on delete cascade,
  provider text not null default 'mock'
    check (provider in ('mock', 'csv', 'approved_fpl', 'licensed')),
  is_enabled boolean not null default true,
  sync_mode text not null default 'manual'
    check (sync_mode in ('manual', 'scheduled')),
  schedule_cron text,
  max_attempts integer not null default 3 check (max_attempts between 1 and 10),
  request_timeout_seconds integer not null default 30
    check (request_timeout_seconds between 5 and 120),
  config jsonb not null default '{}'::jsonb,
  last_successful_sync_at timestamptz,
  last_failed_sync_at timestamptz,
  created_by uuid references public.admin_profiles(id) on delete set null,
  updated_by uuid references public.admin_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (sync_mode <> 'scheduled' or schedule_cron is not null),
  check (provider <> 'csv' or sync_mode = 'manual')
);

create table public.provider_sync_runs (
  id uuid primary key default gen_random_uuid(),
  competition_season_id uuid not null references public.competition_seasons(id) on delete cascade,
  provider text not null
    check (provider in ('mock', 'csv', 'approved_fpl', 'licensed')),
  trigger_source text not null
    check (trigger_source in ('manual', 'csv_upload', 'scheduled', 'retry', 'system_test')),
  status text not null default 'running'
    check (status in ('queued', 'running', 'succeeded', 'partial', 'failed', 'cancelled')),
  idempotency_key text not null unique,
  parent_run_id uuid references public.provider_sync_runs(id) on delete set null,
  attempt_number integer not null default 1 check (attempt_number > 0),
  requested_by uuid references public.admin_profiles(id) on delete set null,
  source_label text,
  raw_record_count integer not null default 0 check (raw_record_count >= 0),
  accepted_record_count integer not null default 0 check (accepted_record_count >= 0),
  rejected_record_count integer not null default 0 check (rejected_record_count >= 0),
  warning_count integer not null default 0 check (warning_count >= 0),
  response_hash text,
  error_summary text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (completed_at is null or completed_at >= started_at)
);

create table public.provider_sync_errors (
  id bigint generated by default as identity primary key,
  sync_run_id uuid not null references public.provider_sync_runs(id) on delete cascade,
  competition_season_id uuid not null references public.competition_seasons(id) on delete cascade,
  provider text not null
    check (provider in ('mock', 'csv', 'approved_fpl', 'licensed')),
  provider_entry_id text,
  external_round_id integer,
  stage text not null
    check (stage in ('configuration', 'fetch', 'parse', 'validation', 'persistence', 'schedule')),
  error_code text not null,
  message text not null,
  retriable boolean not null default false,
  attempt_number integer not null default 1 check (attempt_number > 0),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.score_snapshots
  add column provider text not null default 'mock'
    check (provider in ('mock', 'csv', 'approved_fpl', 'licensed')),
  add column sync_run_id uuid references public.provider_sync_runs(id) on delete set null,
  add column payload_type text not null default 'round_scores'
    check (payload_type in (
      'round_scores',
      'league_standings',
      'entry_profile',
      'round_metadata',
      'provider_health'
    )),
  add column validation_status text not null default 'pending'
    check (validation_status in ('pending', 'valid', 'partial', 'invalid')),
  add column validated_at timestamptz,
  add column metadata jsonb not null default '{}'::jsonb;

create table public.provider_score_records (
  id uuid primary key default gen_random_uuid(),
  sync_run_id uuid not null references public.provider_sync_runs(id) on delete cascade,
  snapshot_id uuid not null references public.score_snapshots(id) on delete restrict,
  competition_season_id uuid not null references public.competition_seasons(id) on delete cascade,
  fantasy_entry_id uuid references public.fantasy_entries(id) on delete set null,
  registration_id uuid references public.registrations(id) on delete set null,
  round_id uuid references public.rounds(id) on delete set null,
  provider text not null
    check (provider in ('mock', 'csv', 'approved_fpl', 'licensed')),
  provider_entry_id text,
  external_round_id integer,
  manager_name text,
  team_name text,
  reported_points integer,
  total_points integer,
  transfer_cost integer not null default 0,
  chip_used text,
  round_rank bigint,
  overall_rank bigint,
  is_provisional boolean not null default true,
  validation_status text not null
    check (validation_status in ('valid', 'warning', 'rejected')),
  validation_errors jsonb not null default '[]'::jsonb,
  raw_record jsonb not null,
  imported_at timestamptz not null default now(),
  unique (sync_run_id, provider_entry_id, external_round_id)
);

create index fantasy_provider_settings_provider_idx
  on public.fantasy_provider_settings (provider, is_enabled);
create index provider_sync_runs_season_started_idx
  on public.provider_sync_runs (competition_season_id, started_at desc);
create index provider_sync_runs_status_idx
  on public.provider_sync_runs (status, started_at desc);
create index provider_sync_runs_parent_run_id_idx
  on public.provider_sync_runs (parent_run_id);
create index provider_sync_errors_run_created_idx
  on public.provider_sync_errors (sync_run_id, created_at desc);
create index provider_sync_errors_season_created_idx
  on public.provider_sync_errors (competition_season_id, created_at desc);
create index provider_score_records_run_status_idx
  on public.provider_score_records (sync_run_id, validation_status);
create index provider_score_records_entry_round_idx
  on public.provider_score_records (
    competition_season_id,
    provider_entry_id,
    external_round_id
  );
create index provider_score_records_fantasy_entry_id_idx
  on public.provider_score_records (fantasy_entry_id);
create index provider_score_records_registration_id_idx
  on public.provider_score_records (registration_id);
create index provider_score_records_round_id_idx
  on public.provider_score_records (round_id);
create index score_snapshots_sync_run_id_idx
  on public.score_snapshots (sync_run_id);

create trigger fantasy_provider_settings_set_updated_at
before update on public.fantasy_provider_settings
for each row execute function public.set_updated_at();

create trigger provider_sync_runs_set_updated_at
before update on public.provider_sync_runs
for each row execute function public.set_updated_at();

insert into public.fantasy_provider_settings (
  competition_season_id,
  provider,
  is_enabled,
  sync_mode,
  config
)
select id, data_provider, true, 'manual', '{}'::jsonb
from public.competition_seasons
on conflict (competition_season_id) do nothing;

create or replace function private.sync_provider_settings_from_season()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  insert into public.fantasy_provider_settings (
    competition_season_id,
    provider,
    is_enabled,
    sync_mode,
    schedule_cron,
    config
  ) values (
    new.id,
    new.data_provider,
    true,
    'manual',
    null,
    '{}'::jsonb
  )
  on conflict (competition_season_id) do update
  set provider = excluded.provider,
      sync_mode = case
        when excluded.provider = 'csv' then 'manual'
        else public.fantasy_provider_settings.sync_mode
      end,
      schedule_cron = case
        when excluded.provider = 'csv' then null
        else public.fantasy_provider_settings.schedule_cron
      end,
      updated_at = now();

  return new;
end;
$$;

revoke all on function private.sync_provider_settings_from_season() from public;

create trigger competition_seasons_sync_provider_settings
after insert or update of data_provider on public.competition_seasons
for each row execute function private.sync_provider_settings_from_season();

comment on table public.fantasy_provider_settings is
  'Non-secret, season-specific configuration for the active fantasy data provider.';
comment on table public.provider_sync_runs is
  'Auditable execution history for manual, CSV, scheduled and retry provider ingestion.';
comment on table public.provider_sync_errors is
  'Structured provider integration errors and validation warnings.';
comment on table public.provider_score_records is
  'Normalized staging records. Phase 8 promotes approved records into round_scores.';
