"use client";

import { useActionState } from "react";
import {
  createAdminUserAction,
  type CreateAdminUserState,
} from "./actions";

const initialState: CreateAdminUserState = {
  error: null,
  success: null,
  email: null,
  temporaryPassword: null,
};

const roles = [
  ["super_admin", "Super Admin"],
  ["competition_manager", "Competition Manager"],
  ["compliance_officer", "Compliance Officer"],
  ["finance_officer", "Finance Officer"],
  ["content_manager", "Content Manager"],
  ["support_officer", "Support Officer"],
  ["auditor", "Auditor"],
] as const;

const inputClass =
  "mt-2 w-full rounded-xl border border-[var(--border)] bg-white px-4 py-3 text-sm text-[var(--brand-strong)] outline-none transition focus:border-[#162a63] focus:ring-4 focus:ring-blue-100";

export function CreateAdminForm() {
  const [state, formAction, pending] = useActionState(
    createAdminUserAction,
    initialState,
  );

  return (
    <div className="rounded-3xl border border-[var(--border)] bg-white p-6 shadow-sm sm:p-7">
      <p className="text-xs font-black uppercase tracking-[0.16em] text-[var(--brand)]">
        New administrator
      </p>
      <h2 className="mt-2 text-2xl font-black text-[var(--brand-strong)]">
        Create admin access
      </h2>
      <p className="mt-3 text-sm leading-6 text-[var(--muted)]">
        Only Super Admins can create staff logins. The temporary password is generated by the server and shown once after a successful creation.
      </p>

      {state.error ? (
        <div className="mt-5 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-red-800">
          {state.error}
        </div>
      ) : null}

      {state.success && state.temporaryPassword && state.email ? (
        <div className="mt-5 rounded-2xl border border-green-200 bg-green-50 p-5 text-green-900">
          <p className="text-sm font-black">{state.success}</p>
          <p className="mt-3 text-xs font-bold uppercase tracking-[0.12em] text-green-800">
            Login email
          </p>
          <p className="mt-1 break-all font-mono text-sm font-bold">{state.email}</p>
          <p className="mt-4 text-xs font-bold uppercase tracking-[0.12em] text-green-800">
            Temporary password — shown once
          </p>
          <p className="mt-1 break-all rounded-xl bg-white px-4 py-3 font-mono text-sm font-black text-[#0e1d49]">
            {state.temporaryPassword}
          </p>
          <p className="mt-3 text-xs leading-5 text-green-800">
            Copy this password securely now. It is not stored in the admin profile or audit log. The administrator should sign in and change it immediately from Account.
          </p>
        </div>
      ) : null}

      <form action={formAction} className="mt-6 space-y-4">
        <label className="block text-sm font-bold text-[var(--brand-strong)]">
          Full name
          <input
            name="full_name"
            required
            minLength={3}
            maxLength={120}
            disabled={pending}
            autoComplete="off"
            className={inputClass}
            placeholder="Staff member's full name"
          />
        </label>

        <label className="block text-sm font-bold text-[var(--brand-strong)]">
          Email address
          <input
            type="email"
            name="email"
            required
            maxLength={254}
            disabled={pending}
            autoComplete="off"
            className={inputClass}
            placeholder="staff@vultme.io"
          />
        </label>

        <label className="block text-sm font-bold text-[var(--brand-strong)]">
          Administrator role
          <select name="role" required disabled={pending} defaultValue="support_officer" className={inputClass}>
            {roles.map(([value, label]) => (
              <option key={value} value={value}>
                {label}
              </option>
            ))}
          </select>
        </label>

        <button
          type="submit"
          disabled={pending}
          className="w-full rounded-xl bg-[#162a63] px-5 py-3 text-sm font-black text-white shadow-lg shadow-blue-950/15 transition enabled:hover:bg-[#0e1d49] disabled:cursor-not-allowed disabled:bg-slate-400"
        >
          {pending ? "Creating administrator..." : "Create admin user"}
        </button>
      </form>
    </div>
  );
}
